version: '3'

networks: 
    laravel:

services: 
    lara_nginx: 
        image: nginx:1.19.9
        container_name: Laravel_Nginx
        ports : 
            - "80:80"
        volumes: 
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - lara_php
            - lara_mysql
        networks: 
            - laravel

    lara_mysql:
        container_name: Laravel_Mysql
        image: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: curiosity
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    lara_php:
        container_name: Laravel_PHP_FPM
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
        ports:
            - "9002:9002"
        volumes: 
            - ./:/var/www/html
        networks: 
            - laravel
        
    lara_redis:  # New Redis service definition
        container_name: Laravel_Redis
        image: redis
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - ./docker/redis:/data
        networks:
        - laravel
        