version: '3'

services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # Nginx web server
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel_network

  # MySQL database
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  dbdata:
